### Numpy

In [1]:
import numpy as np

#### Array 만들기

In [2]:
# List -> Array
data1 = [6, 7.5, 8, 0, 1]
data1

[6, 7.5, 8, 0, 1]

In [5]:
# numpy를 이용하여 1차원 배열로 변형하기
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [13]:
# 배열의 크기 확인
arr1.shape # 데이터의 크기 
# (5) => 정수 , (5,) => 튜플

(5,)

In [15]:
list01=[
       [
        [1, 2, 3, 4],
        [5, 6, 7, 8]
    ]
]
list01

[[[1, 2, 3, 4], [5, 6, 7, 8]]]

In [14]:
# 2차원 리스트 
arr2 = np.array(
    [
        [1, 2, 3, 4],
        [5, 6, 7, 8]
    ]
)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [16]:
arr2.shape

(2, 4)

In [21]:
# 3차원 리스트 
arr3 = np.array(
   [ 
    [
        [1, 2, 3, 4],
        [5, 6, 7, 8]
    ],
    [
        [1, 2, 3, 4],
        [5, 6, 7, 8]
    ],
    [
        [1, 2, 3, 4],
        [5, 6, 7, 8]
    
    ]
   ]    
)

arr3

array([[[1, 2, 3, 4],
        [5, 6, 7, 8]],

       [[1, 2, 3, 4],
        [5, 6, 7, 8]],

       [[1, 2, 3, 4],
        [5, 6, 7, 8]]])

In [22]:
arr3.shape 
# (3, 2, 4) -> page, row, column

(3, 2, 4)

In [33]:
# 0으로 구성된 1차원 array 생성
np.zeros(5)

# 0으로 구성된 2차원 array(3,5) 생성
np.zeros([2,5])

# 3차
np.zeros((3, 4, 5))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])