### Series
- 데이터가 순차적으로 나열된 1차원 배열의 형태

In [6]:
import pandas as pd

In [2]:
# Dictionary -> Series
dict_data = {
    'a' : 1,
    'b' : 2,
    'c' : 3,
}
dict_data

{'a': 1, 'b': 2, 'c': 3}

In [10]:
sr = \
    pd.Series(
        dict_data
    )
sr

a    1
b    2
c    3
dtype: int64

---


In [92]:
# List -> series

list_data ={
        'r' : '2026-01-01',
        'm' : '3.14',
        'm2' : 'abc',
        'n' : '100',
        'mf' : 'True'
    }
list_data


{'r': '2026-01-01', 'm': '3.14', 'm2': 'abc', 'n': '100', 'mf': 'True'}

In [89]:
pd.Series(
    list_data
)

r    2026-01-01
m          True
dtype: str

In [22]:
# Tuple -> Series변환 후 index 변경하기

tuple_data = ('유비', '2020-10-20', '남', False)
sr = pd.Series(
    tuple_data,
    index=['이름', '생년월일', '성별', '학생여부']
)
sr

이름              유비
생년월일    2020-10-20
성별               남
학생여부         False
dtype: object

In [25]:
tuple_data = ('유비', '2020-10-20', '남', False)
sr = pd.Series(
    tuple_data
)
sr.index = ['이름', '생년월일', '성별', '학생여부']
sr

이름              유비
생년월일    2020-10-20
성별               남
학생여부         False
dtype: object

In [87]:
# iloc로 추출하기
sr.iloc[:2]

# loc로 추출하기
sr.loc[['이름', '생년월일']]  # series 는 1차원

이름              유비
생년월일    2020-10-20
dtype: object

---
#### Series의 연산

In [65]:
student = pd.Series(
    {
        '국어':100,
        '영어':80,
        '수학':90
    }
)
student


국어    100
영어     80
수학     90
dtype: int64

In [66]:
# 과목의 점수를 200으로 나누기

student / 200

국어    0.50
영어    0.40
수학    0.45
dtype: float64

In [67]:
student1 = pd.Series(
    {
        '국어':100,
        '영어':80,
        '수학':90
    }
)
student1


국어    100
영어     80
수학     90
dtype: int64

In [68]:
student2 = pd.Series(
    {
        '수학':80,
        '국어':90,
        '영어':80,
    }
)
student2


수학    80
국어    90
영어    80
dtype: int64

In [ ]:
# 덧셈
addition = student1 + student2
addition

국어    190
수학    170
영어    160
dtype: int64

In [71]:
# 뺄셈
subtraction = student1 - student2
subtraction

국어    10
수학    10
영어     0
dtype: int64

In [72]:
# 곱셈
multiplication = student1 * student2
multiplication

국어    9000
수학    7200
영어    6400
dtype: int64

In [73]:
# 나눗셈
division = student1 / student2
division

국어    1.111111
수학    1.125000
영어    1.000000
dtype: float64

In [77]:
# 데이터프레임 만들기
result = \
    pd.DataFrame(
        [addition, subtraction, multiplication, division],
        index=['덧셈', '뺄셈', '곱셈', '나눗셈']    
    )
result

국어        수학      영어
덧셈    190.000000   170.000   160.0
뺄셈     10.000000    10.000     0.0
곱셈   9000.000000  7200.000  6400.0
나눗셈     1.111111     1.125     1.0

In [79]:
result = \
    pd.DataFrame(
        [addition, subtraction, multiplication, division],
        
    )
result.index = ['덯', '마','곱', '난']
result

국어        수학      영어
덯   190.000000   170.000   160.0
마    10.000000    10.000     0.0
곱  9000.000000  7200.000  6400.0
난     1.111111     1.125     1.0

---
### NaN (Not a number : 결측치) 값이 있는 연산

In [ ]:
import numpy as np

# 파이썬에서 nan만들 수 있는건 numpy밖에 없음.

In [7]:
student1 = pd.Series(
    {
        '국어': np.nan,
        '수학':90,
        '영어':80
    }
)
student1

국어     NaN
영어    80.0
수학    90.0
dtype: float64

In [9]:
student2 = pd.Series(
    {
        '수학':80,
        '국어':90,
    
    }
)
student2

수학    80
국어    90
dtype: int64

In [14]:
# 덧셈, 뺄셈, 곱셈, 나눗셈
addition = student1 + student2
subtraction = student1 - student2
multiplication = student1 * student2
division = student1 / student2
# NaN값이 들어간 곳은 NaN을 반환

In [16]:
# DataFrame 만들기
result = \
    pd.DataFrame(
        [addition, subtraction, multiplication, division],
        
    )
result


국어        수학  영어
0 NaN   170.000 NaN
1 NaN    10.000 NaN
2 NaN  7200.000 NaN
3 NaN     1.125 NaN

In [17]:
# NaN은 다른값으로 대체하기.(NaN -> 0)
addition = student1.add(student2, fill_value=0) # NaN이 발생하면 ~~로 채우겠음.
subtraction = student1.sub(student2, fill_value=0)
multiplication = student1.mul(student2, fill_value=0)
division = student1.div(student2, fill_value=0)

In [18]:
# DataFrame 만들기
result = \
    pd.DataFrame(
        [addition, subtraction, multiplication, division],
        
    )
result  # 영어의 나눗셈인 경우에는 80을 0으로 나누어 inf(infinity:무한대)가 발생


국어        수학    영어
0  90.0   170.000  80.0
1 -90.0    10.000  80.0
2   0.0  7200.000   0.0
3   0.0     1.125   inf

In [20]:
# 1로만 구성된 1차원 array
np.ones(5)
np.ones((3,5)) # T -> 1 F -> 0

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [28]:
# 10으로 구성된 1차원 array 5개 생성
np.ones(5) * 10
# ==
np.full(5, 10)

array([10, 10, 10, 10, 10])

In [36]:
np.ones([3, 5]) *10
# ==
# np.full

array([[10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10.]])

In [48]:
# 범위의 숫자 array 생성
len(np.arange(0, 1+1, 0.01))
# len보다 shape 가 빠름, 실수나오면 shape사용 추천쓰.
(np.arange(0, 1+1, 0.01)).shape[0]


200

In [53]:
arr1 = np.arange(0, 1+1, 0.01)
arr1[0:4+1]

array([0.  , 0.01, 0.02, 0.03, 0.04])

In [56]:
arr1.dtype

dtype('float64')

In [59]:
# array생성시 Data Type을 정의하면서 array 생성
arr2 = np.array([1, 2, 3, 4, 5], dtype = np.float64)
arr2.dtype

# read 하면서 만들 수 있는거, 만들고 나서 만들 수 있는 방법 2가지.

dtype('float64')

In [61]:
arr3 = np.array([1,2, 3, 4, 5])
arr3 = arr3.astype(np.float64)
arr3.dtype

dtype('float64')

---
#### 연산

In [71]:
# np.float64로 array 만들기
arr1 = np.array(
    [
        [
            1, 2, 3
        ],
        [
            4, 5, 6
        ]
    ],
    dtype=np.float64
)
arr1

array([[1., 2., 3.],
       [4., 5., 6.]])

In [72]:
# np.float64로 array 만들기
arr2 = np.array(
    [
        [
            7,8,9
        ],
        [
            10,11,12
        ]
    ],
    dtype=np.float64
)
arr2

array([[ 7.,  8.,  9.],
       [10., 11., 12.]])

In [79]:
arr1 + arr2
arr1 - arr2
arr1 * arr2
arr1 / arr2

array([[0.14285714, 0.25      , 0.33333333],
       [0.4       , 0.45454545, 0.5       ]])

In [84]:
# arr1의 제곱 및 제곱근
arr1 ** 2
np.pow(arr1, 2) # 제곱 power
np.sqrt(arr1) # 제곱근
np.sqrt(np.pow(arr1, 2)) # 제곱의 제곱근 

array([[1., 2., 3.],
       [4., 5., 6.]])

---
#### Data Handling

In [86]:
arr = np.arange(10, 20+1)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [95]:
arr[5]
arr[5:8+1]
arr[5:8+1] = [100, 102, 4,3]
arr

array([ 10,  11,  12,  13,  14, 100, 102,   4,   3,  19,  20])

### 2차원 배열

In [101]:
# 2차원 Array 생성하기
arr2d = np.array(
    [
        [1, 2, 3, 4],
        [5, 6, 7, 8],
        [9, 10, 11, 12],
        [13, 14, 15, 16],
    ]
)
arr2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [105]:
arr2d[2,:]

array([ 9, 10, 11, 12])

In [112]:
arr2d[1:2+1, :]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [113]:
arr2d[:,0:1+1]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14]])

In [115]:
arr2d[:, range(0,1+1)]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14]])

In [121]:
arr2d[0:1+1,1:2+1] = [0]
arr2d

array([[ 1,  0,  0,  4],
       [ 5,  0,  0,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

---
#### reshape (머신러닝에서 무조건 씀)
###### 1차원으로 학습시켜서 2차원으로 변형

In [133]:
# 1부터 8까지의 array
arr = np.arange(1, 8+1)
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [124]:
# arr을 2차원으로 변경
np.reshape(arr, (2, 4))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [130]:
arr2 = np.arange(0, 15+1)
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [143]:
np.reshape(arr2, (4, 4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [139]:
# arr을 3차원 변경 : (page, row, column)

arr3 = np.reshape(arr, (2,2,2))
print(arr3)
print(arr3.shape)


[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
(2, 2, 2)


In [157]:
# 2차원 배열을 1차원 변경
arr4 = np.reshape(arr2, (4, 4))
arr5 = arr4.reshape(-1, 1)  # 밖의 []를 버리지 않아서 2차원처럼 보이지만 1차원임.
arr5

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15]])

In [158]:
arr = np.arange(1, 12+1)
arr


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [159]:
arr2 = np.reshape(arr, (2, 2, 3))
arr2

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [161]:
arr3 = arr2.reshape( -1, 1,1)
arr3.shape

(12, 1, 1)